### ISSUE TITLE
moose.seed(seed) unexpected behaviour 

### ISSUE THREAD

**Issue by rahulgayatri23** [BhallaLab/moose-core#129]
The moose.seed(seed) function, which uses the same seed instead of random seed generator is not working on the ghevar machine. It works on nargis though. It is the same multithreaded branch on both the servers.

**Comment by subhacom** [comment]
Since the problem appears on a specific installation, it is probably a system configuration issue rather than a bug in the program.

The first thing to check in this kind of situation is whether you have multiple copies of the module installed at different locations and Python is picking up the wrong one.
Try
`import moose
print moose.__file__
`
to see the full path of the file loaded for moose module. If you are using a system with `updatedb` and `locate` installed, then try:
`sudo updatedb
locate moose.py
`
to display all files named moose.py on the system. This may also show if you have multiple installs.

The next thing to check is the build configurations on the two systems. There was a recent switch to Boost libraries. Is there a switch in the build system between boost and built-in function for seeding? Are you using different settings for this on the two systems? Is it possible that the code for reseeding the RNG was not updated and keeps reseeding a different RNG instead of the one used in the rand() [or equivalent] function?

You need to put more detail of the system in your bug report. Just noting that it works on computer A but does not work on B will not allow the public without access to those systems to figure it out. In case all you want is local help on your systems, it does not make sense to put the problem up publicly as a bug report.
For better resolution, try to think what could be relevant for someone to reproduce and figure out the problem, e.g. what version of OS were you using? What were the libraries linked to the binaries on each system? (Use ldd {wherever it is located}/_moose.so). Such information helps the developers to narrow down on the issue.

**Comment by rahulgayatri23** [comment]
The problem occurred due to the difference in the number of subdivisions in the mesh set in the python script.
When the number of subdivisions in the mesh, i.e., CubeMesh.nx is 1, moose.seed(seed) function generates the same random number everytime. 
But if the number of subdivisions increases, we cannot expect the same behavior.

**Comment by dilawar** [comment]
From @upibhalla 

Random number may be reseeded at reinit. 

I think that the random number generator is automatically reseeded at reinit. I don't have a clear picture of where in the code it would be reseeded but I found that adding another moose.seed( seed ) call after reinit helped to make the outcome consistent.
