### ISSUE TITLE
`moose.Func` vs `moose.Function`

### ISSUE THREAD

**Issue by dilawar** [BhallaLab/moose-core#366]
Hi @subhacom 
We have two classes which seems to me are doing the same thing: `moose.Func` and `moose.Function`. Is it right? 

If `moose.Function` is more general, can we remove `moose.Func`? Any other thoughts?

**Comment by subhacom** [comment]
Func was the initial version of the feature and Function was an improved version. The field signatures are slightly different - Func can take 2 or 3 variable messages (xy, xyz). I would suggest checking the existing scripts and use cases to see if Func has any practical utility. Otherwise just deprecate it.

**Comment by dilawar** [comment]
Thank you @subhacom . I'll remove this class and the example scripts from `moose-example` repositories. I don't think it has been used in `rdesigneur` or other prominent places.

**Comment by dilawar** [comment]
This is removed in #387
